# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526b6e8fe8766ce707316cbbf5445a06eb6d3f9aea94f28cef497c84928b5fdab80c8987178745c310f74431b682336398706caa5da8318e92a3f87d7d441931

test:
  secret_key_base: c27da4c8e89a33fe0979744b3595366523ad3238ad4ad75d4f335657c6f5323cd13856091cafe8a99ba056bfce3ab181daa4996d190e9d14612fbd2e645bc90c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
